openapi: 3.0.3
info:
  title: 'API - Sistema de Pontos'
  description: 'API para o sistema de pontos.'
  version: 1.0.0
servers:
  -
    url: 'http://localhost:8000'
paths:
  /api/login:
    post:
      summary: 'Criar token.'
      operationId: criarToken
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: mallory05@example.net
                password:
                  type: string
                  description: ''
                  example: repellendus
              required:
                - email
                - password
      security: []
  /api/logout:
    delete:
      summary: 'Revoga o token atual.'
      operationId: revogaOTokenAtual
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
  /api/user:
    get:
      summary: 'Ver usuário atual.'
      operationId: verUsurioAtual
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: 2
                    name: 'Grayson Greenfelder'
                    email: qcrooks@example.com
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 2
                      name:
                        type: string
                        example: 'Grayson Greenfelder'
                      email:
                        type: string
                        example: qcrooks@example.com
      tags:
        - Endpoints
  /api/time-entries:
    get:
      summary: 'Lista os pontos do usuário atual.'
      operationId: listaOsPontosDoUsurioAtual
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      id: 1
                      started_at: '2024-03-19T01:52:25.000000Z'
                      ended_at: null
                    -
                      id: 2
                      started_at: '2024-03-19T02:09:08.000000Z'
                      ended_at: null
                properties:
                  data:
                    type: array
                    example:
                      -
                        id: 1
                        started_at: '2024-03-19T01:52:25.000000Z'
                        ended_at: null
                      -
                        id: 2
                        started_at: '2024-03-19T02:09:08.000000Z'
                        ended_at: null
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1
                        started_at:
                          type: string
                          example: '2024-03-19T01:52:25.000000Z'
                        ended_at:
                          type: string
                          example: null
      tags:
        - Endpoints
    post:
      summary: 'Registra um novo ponto.'
      operationId: registraUmNovoPonto
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: 1
                    started_at: '2024-03-19T02:42:09.000000Z'
                    ended_at: null
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      started_at:
                        type: string
                        example: '2024-03-19T02:42:09.000000Z'
                      ended_at:
                        type: string
                        example: null
      tags:
        - Endpoints
  '/api/time-entries/{entry_id}':
    put:
      summary: 'Atualiza um ponto (marca como finalizado).'
      operationId: atualizaUmPontomarcaComoFinalizado
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: 1
                    started_at: '2024-03-19T02:21:31.000000Z'
                    ended_at: null
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      started_at:
                        type: string
                        example: '2024-03-19T02:21:31.000000Z'
                      ended_at:
                        type: string
                        example: null
      tags:
        - Endpoints
    parameters:
      -
        in: path
        name: entry_id
        description: 'The ID of the entry.'
        example: 19
        required: true
        schema:
          type: integer
tags:
  -
    name: Endpoints
    description: ''
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: ''
security:
  -
    default: []
